import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const redditSans = localFont({
    src: "./fonts/RedditSansCondensed-Regular.ttf",
    variable: "--font-reddit-sans",
    weight: "100 900"
})

const redditBold = localFont({
    src: "./fonts/RedditSansCondensed-Bold.ttf",
    variable: "--font-reddit-bold",
    weight: "600"
})

export const metadata: Metadata = {
  title: "Car Dealer App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${redditSans.variable} ${redditBold.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
